# Generated by Django 3.1.2 on 2021-04-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Do_Ident', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='TestPaper',
        ),
    ]
