# Generated by Django 3.1.2 on 2021-04-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Do_Ident', '0002_auto_20210430_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='body',
        ),
        migrations.AddField(
            model_name='testpaper',
            name='index',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='result',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
