# Generated by Django 3.1.2 on 2021-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Do_Ident', '0006_auto_20210430_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='index',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
