# Generated by Django 3.1.2 on 2021-04-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Do_Ident', '0007_auto_20210430_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpaper',
            old_name='index',
            new_name='paper_idx',
        ),
    ]
